name: release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  release:
    name: Create a GH Release
    runs-on: self-hosted
    steps:
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: false
        draft: true
        fail_on_unmatched_files: true
        discussion_category_name: Announcements
        name: ${{ github.ref_name }}